[workspace]
resolver = "2"
members = ["core", "service", "client", "ui"]

[profile.release]
opt-level = "z"
#debug = "limited"
strip = "symbols"
debug-assertions = false
overflow-checks = false
lto = "fat"
#panic = "abort"
incremental = false
codegen-units = 1
