[package]
name = "tablet-assist"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1"
argp = "0.3"
libc = "0.2"
log = "0.4"
env_logger = "0.10"
smol = "1"
smol-potat = "1"
async-io = "2"
async-signal = "0.2"
signal-hook = "0.3"
zbus = "3"
toml = "0.8"

[dependencies.input]
version = "0.8"
optional = true

[dependencies.industrial-io]
version = "0.5"
optional = true

[dependencies.serde]
version = "1"
features = ["derive"]

[dependencies.tablet-assist-core]
path = "../core"

[features]
default = ["input", "industrial-io"]
