[package]
name = "tablet-assist-service"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror.workspace = true
log.workspace = true
env_logger.workspace = true
libc.workspace = true
argp.workspace = true
smol.workspace = true
smol-potat.workspace = true
async-signal.workspace = true
signal-hook.workspace = true
zbus.workspace = true
serde.workspace = true
toml.workspace = true

[dependencies.input]
workspace = true
optional = true

[dependencies.udev]
workspace = true
optional = true

[dependencies.glam]
workspace = true
optional = true

[features]
default = ["input", "iio"]
iio = ["udev", "glam"]
