[package]
name = "tablet-assist-agent"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1"
log = "0.4"
env_logger = "0.10"
smol = "2"
smol-potat = "1"
async-signal = "0.2"
signal-hook = "0.3"
zbus = "3"
toml = "0.8"
dirs = "5"

[dependencies.serde]
version = "1"
features = ["derive"]

[dependencies.x11rb]
package = "x11rb-async"
version = "0.13"
default-features = false
features = ["randr", "xinput"]

[dependencies.tablet-assist-service]
path = "../service"
